APP_SERVICE = "app"
WEB_SERVICE = "web"


def _quote(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def _env_lines(env: dict[str, str], indent: str) -> list[str]:
    return [f"{indent}{key}: {_quote(value)}" for key, value in sorted(env.items())]


def service_env(services: list[dict]) -> dict[str, str]:
    env = {}
    for service in services:
        host_env = service.get("host_env")
        if host_env:
            env[host_env] = service["name"]
    return env


def render_compose(project: str, services: list[dict], processes: list[dict]) -> str:
    app_env = {
        "ENV_FOR_DYNACONF": "development",
        "POSTGRES_USER": "${POSTGRES_USER:-genesis}",
        "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD:-genesis}",
        "POSTGRES_DB": "${POSTGRES_DB:-genesis}",
        **service_env(services),
    }

    lines = [
        "# ==== INFRA — generated by genesis, do not edit ====",
        "services:",
        f"  {APP_SERVICE}:",
        f"    image: ${{IMAGE_NAME:-{project}}}:${{IMAGE_TAG:-latest}}",
        "    build:",
        "      context: .",
        "    command: uv run --no-sync uvicorn genesis.main:app --host 0.0.0.0 --port 8000",
        "    working_dir: /app/backend",
        "    environment:",
        *_env_lines(app_env, "      "),
        "    env_file:",
        "      - path: .env",
        "        required: false",
        "    depends_on:",
        *[f"      - {service['name']}" for service in services],
        "",
    ]

    for process in processes:
        if process["name"] in ("fastapi", "nginx"):
            continue
        lines += [
            f"  {process['name']}:",
            f"    image: ${{IMAGE_NAME:-{project}}}:${{IMAGE_TAG:-latest}}",
            f"    command: {process['command']}",
            "    working_dir: /app/backend",
            "    environment:",
            *_env_lines(app_env, "      "),
            "    env_file:",
            "      - path: .env",
            "        required: false",
            "    depends_on:",
            f"      - {APP_SERVICE}",
            "",
        ]

    lines += [
        f"  {WEB_SERVICE}:",
        f"    image: ${{IMAGE_NAME:-{project}}}:${{IMAGE_TAG:-latest}}",
        '    command: /usr/sbin/nginx -g "daemon off;"',
        "    ports:",
        '      - "8000:80"',
        "    depends_on:",
        f"      - {APP_SERVICE}",
        "",
    ]

    for service in services:
        name = service["name"]
        lines += [
            f"  {name}:",
            f"    image: {service['image']}",
        ]
        env = service.get("environment", {})
        if env:
            lines += ["    environment:", *_env_lines(env, "      ")]
        if service.get("data_dir"):
            lines += ["    volumes:", f"      - {project}_{name}:{service['data_dir']}"]
        lines.append("")

    volumes = [s["name"] for s in services if s.get("data_dir")]
    if volumes:
        lines.append("volumes:")
        lines += [f"  {project}_{name}:" for name in volumes]

    return "\n".join(lines) + "\n"
