import json

BANNER = "<!-- Generated by `genesis docs`. Do not edit; your changes will be overwritten. -->"


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_none_\n"
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines) + "\n"


def render_genesis_json(graph: dict) -> str:
    return json.dumps(graph, indent=2, sort_keys=True) + "\n"


def render_project(graph: dict) -> str:
    installed = graph["modules"]["installed"]
    summaries = graph["modules"]["summaries"]
    return f"""{BANNER}

# Project

A Genesis application: a React frontend, a FastAPI backend, and Postgres, assembled from
modules. Everything auto-wires by convention — there are no registration lists to edit.

## What is installed

{_table(["Module", "Purpose"], [[name, summaries.get(name, "")] for name in installed])}
## Size

| Thing | Count |
| --- | --- |
| Database tables | {len(graph["tables"])} |
| Request/response shapes | {len(graph["shapes"])} |
| Endpoint files | {len(graph["endpoints"])} |
| Routes | {sum(len(item["routes"]) for item in graph["endpoints"])} |
| Background tasks | {len(graph["tasks"])} |
| Frontend pages | {len(graph["pages"])} |

## Run it

```bash
manage dev      # build and start at http://localhost:8000
manage down     # stop
manage logs     # follow logs
```

See `ARCHITECTURE.md` for how a request flows, `AI_CONTEXT.md` for where to put new code.
"""


def render_architecture(graph: dict) -> str:
    services = _table(
        ["Service", "Capability", "Port"],
        [
            [item["name"], item["capability"] or "—", str(item["port"] or "—")]
            for item in graph["services"]
        ],
    )
    return f"""{BANNER}

# Architecture

```
frontend (React)  ->  app/endpoints/<feature>.py  ->  genesis facade  ->  app/models/ (database)
   pages/*.tsx           routing only               db · cache · ai …     one table per file
```

## Layers

- `backend/app/` — your code. Endpoints, models, tasks. Auto-discovered at startup.
- `backend/genesis/` — the kernel and facade. Infrastructure; do not edit.
- `frontend/src/pages/` — one page per file, auto-routed from its `route` export.

Discovery happens once at startup in `genesis/loader.py`, which wires models, tasks and
endpoints, then logs what it found. Run `genesis map` to see the resolved graph without
starting the app.

## Services

{services}
## Topology

The same application image runs either as one container with every service inside it, or as
separate compose services. Service addresses are env-driven and default to `127.0.0.1`, so
only environment values differ between the two.
"""


def render_api(graph: dict) -> str:
    rows = []
    for endpoint in graph["endpoints"]:
        for route in endpoint["routes"]:
            path = f"/api/v1{endpoint['prefix']}{route['path']}"
            rows.append(
                [
                    route["method"],
                    f"`{path}`",
                    route["response_model"] or "—",
                    str(route["status_code"] or 200),
                    f"`{endpoint['file']}`",
                ]
            )
    return f"""{BANNER}

# API

Every endpoint declares a `response_model`, which keeps the OpenAPI schema complete — the
frontend generates its types from it.

{_table(["Method", "Path", "Response", "Status", "File"], rows)}
Kernel endpoints (`genesis/main.py`, not yours to edit): `/api/health`, `/api/status`,
`/api/me`, `/api/openapi.json`, `/api/redoc`.
"""


def render_database(graph: dict) -> str:
    sections = []
    for table in graph["tables"]:
        columns = _table(
            ["Column", "Type", "Nullable"],
            [[column["name"], column["type"], "yes" if column["null"] else "no"] for column in table["columns"]],
        )
        sections.append(f"### `{table['table']}`\n\nModel `{table['model']}` in `{table['file']}`\n\n{columns}")
    body = "\n".join(sections) if sections else "_no tables_\n"

    shapes = _table(
        ["Shape", "Fields", "File"],
        [
            [shape["shape"], ", ".join(field["name"] for field in shape["fields"]) or "—", f"`{shape['file']}`"]
            for shape in graph["shapes"]
        ],
    )

    return f"""{BANNER}

# Database

Models are Peewee classes; every column below comes from a `db.*` field. Schema changes are
versioned with peewee-migrate and applied automatically at startup. Never hand-write DDL —
run `manage migrate "describe change"`.

## Tables

{body}
## Request / response shapes

Shapes live beside the table they describe, or in their own `app/models/<concept>.py` when no
table backs them.

{shapes}"""


def render_modules(graph: dict) -> str:
    installed = set(graph["modules"]["installed"])
    rows = [
        [
            name,
            "installed" if name in installed else "available",
            graph["modules"]["summaries"].get(name, ""),
        ]
        for name in graph["modules"]["available"]
    ]
    return f"""{BANNER}

# Modules

A module is a capability with its own files, dependencies and services, declared in
`modules/<name>/module.toml`. Nothing in a manifest registers a route, model, task or nav
entry — runtime conventions already do that, so composing a project is adding or removing
files. Only infrastructure needs rendering.

{_table(["Module", "State", "Purpose"], rows)}
Render a project without a module:

```bash
genesis render --out ../my-app --without jobs
```
"""


def render_ai_context(graph: dict) -> str:
    pages = _table(
        ["Route", "Nav", "File"],
        [[f"`{page['route']}`", page["nav"] or "—", f"`{page['file']}`"] for page in graph["pages"]],
    )
    tasks = _table(["Task", "File"], [[item["task"], f"`{item['file']}`"] for item in graph["tasks"]])
    return f"""{BANNER}

# AI context

Read `genesis.json` first — it is this document in machine-readable form.

## Where to put things

| To add… | Create | It becomes |
| --- | --- | --- |
| an endpoint | `backend/app/endpoints/<feature>.py` with `api = router("/x")` | `/api/v1/x`, auto-mounted |
| a table | `backend/app/models/<concept>.py` with a `db.Model` | a table, auto-discovered |
| a request shape | the same `app/models/<concept>.py` | validation on the endpoint |
| a background task | `backend/app/tasks/<name>.py` with `@task` | registered on the worker |
| a page | `frontend/src/pages/<Name>.tsx` exporting `route` | a route, and nav if it exports `nav` |

## Invariants

- Every data shape lives in `app/models/`. Endpoints contain routing only — no Pydantic classes.
- Every endpoint declares `response_model`; the frontend's types are generated from the schema.
- Never hand-write a frontend type for an API shape; use `Schema<"Name">` from `@/lib/api`.
- Never hand-write SQL DDL or edit the database directly; generate a migration.
- Import from `genesis`, never from `genesis.core` or `genesis.services`.
- Do not edit `backend/genesis/**`, `deploy/**`, `Dockerfile`, `docker-compose.yml`,
  `backend/settings.toml`, or any file with a generated-do-not-edit banner.

## Current pages

{pages}
## Current tasks

{tasks}
## Definition of done

```bash
cd backend && uvx ruff check .
cd frontend && npm run build
genesis check
```
"""


RENDERERS = {
    "genesis.json": render_genesis_json,
    "PROJECT.md": render_project,
    "ARCHITECTURE.md": render_architecture,
    "API.md": render_api,
    "DATABASE.md": render_database,
    "MODULES.md": render_modules,
    "AI_CONTEXT.md": render_ai_context,
}


def render_all(graph: dict) -> dict[str, str]:
    return {name: renderer(graph) for name, renderer in RENDERERS.items()}
