from pathlib import Path

from genesis_cli.docs import render_all
from genesis_cli.scan import scan

TEMPLATE = Path(__file__).resolve().parents[3]
GRAPH = scan(TEMPLATE)


def test_finds_the_items_table_with_its_columns():
    items = next(table for table in GRAPH["tables"] if table["table"] == "items")
    assert items["model"] == "Item"
    columns = {column["name"]: column for column in items["columns"]}
    assert set(columns) == {"name", "description", "created_at"}
    assert columns["description"]["null"] is True
    assert columns["name"]["null"] is False


def test_finds_shapes_outside_tables():
    shapes = {shape["shape"] for shape in GRAPH["shapes"]}
    assert {"ItemCreate", "ItemRead", "ChatRequest", "JobStart", "ItemsSummary"} <= shapes


def test_no_shape_is_declared_in_an_endpoint_file():
    assert not [shape for shape in GRAPH["shapes"] if "endpoints" in shape["file"]]


def test_routes_carry_method_path_and_response_model():
    routes = {
        f"{route['method']} /api/v1{endpoint['prefix']}{route['path']}": route
        for endpoint in GRAPH["endpoints"]
        for route in endpoint["routes"]
    }
    assert "GET /api/v1/items" in routes
    assert routes["GET /api/v1/items"]["response_model"] == "list[ItemRead]"
    assert routes["POST /api/v1/items"]["status_code"] == 201


def test_every_route_declares_a_response_model_or_returns_no_content():
    untyped = [
        f"{route['method']} {endpoint['prefix']}{route['path']}"
        for endpoint in GRAPH["endpoints"]
        for route in endpoint["routes"]
        if not route["response_model"] and route["status_code"] != 204
    ]
    assert not untyped, untyped


def test_finds_tasks_and_pages():
    assert {task["task"] for task in GRAPH["tasks"]} == {"demo_sleep"}
    routes = {page["route"] for page in GRAPH["pages"]}
    assert {"/", "/jobs", "/chat", "/analytics", "/status", "/admin/*", "/auth"} == routes


def test_services_carry_capabilities():
    capabilities = {
        service["name"]: service["capability"] for service in GRAPH["services"]
    }
    assert capabilities["postgres"] == "database"
    assert capabilities["valkey"] == "cache"
    assert capabilities["temporal"] == "jobs"


def test_render_is_deterministic():
    assert render_all(GRAPH) == render_all(scan(TEMPLATE))


def test_every_document_carries_the_generated_banner():
    for name, content in render_all(GRAPH).items():
        if name.endswith(".md"):
            assert content.startswith("<!-- Generated by")


def test_generated_docs_mention_real_routes():
    api = render_all(GRAPH)["API.md"]
    assert "/api/v1/items" in api
    assert "backend/app/endpoints/items.py" in api
